### ISSUE TITLE
add game start on enter or space key

### ISSUE THREAD

**Issue by MaximKondratev** [akhmadullin/snake#1]
add game start on enter or space key

**Comment by akhmadullin** [comment]
hey, @MaximKondratev

thanks for your idea!

add a solution in https://github.com/akhmadullin/snake/pull/2 - now it's possible to start, pause, continue or generate new game by Space/Enter keydown.

**Comment by akhmadullin** [comment]
@MaximKondratev, how do you think, mb we should add ability to continue game by arrow keydown, when game is paused?

**Comment by MaximKondratev** [comment]
definitely yes!

**Comment by akhmadullin** [comment]
Nice!

I've merged #2

[Check it out!](https://akhmadullin.github.io/snake/)
