### ISSUE TITLE
Game is over if I move the snake too fast

### ISSUE THREAD

**Issue by ilyadonskoy** [akhmadullin/snake#3]
I was playing snake game and one thing is really got me up. If I hit arrow keys and move the snake to the opposite direction then it starts to eat itself. Is it a bug or a feature? Please watch attachment video to see detail

https://user-images.githubusercontent.com/20411284/142853952-89b24d1c-1742-4c04-adb7-75e941818a62.mov

**Comment by akhmadullin** [comment]
Hi, @FeltBoots!

Thanks for your feedback - yes, it's a bug.

I'll fix it soon.

**Comment by akhmadullin** [comment]
@FeltBoots, the bug is fixed.

[Check it](https://akhmadullin.github.io/snake/).

Have a nice game :)
